### Start command
POST http://10.20.121.231:5050/api/mqtt/cmd/start


### Stop command
POST http://10.20.121.231:5050/api/mqtt/cmd/stop
Content-Type: application/json

{
    "video": ".mp4"
}


### Stop command without video upload
POST http://10.20.121.231:5050/api/mqtt/cmd/stop-no-video

